# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
    - name: Make the release 
      run: |
        ./bin/make_release test.00 8000
    - name: Install dependencies
      run: |
        pushd release/test.00
        pwd
        python -m pip install --upgrade pip
        pip install pytest
        pushd python
        pwd
        pip install -r requirements.txt
    - name: Run the server and test with client 
      run: |
        pushd release/test.00
        pwd
        python gtkserver.py localhost.yaml &
        sleep 5
        pushd python
        pytest test_gentk.py 
